### ISSUE TITLE
useless "ln" deletion

### ISSUE THREAD

**Issue by tzawlxih** [ironPeakServices/hardened-alpine#2]
deleting "ln" or any other busybox symlinks create fake self confidence, 
because they easily can be restored `cp /bin/busybox /bin/ln`

**Comment by hazcod** [comment]
Hi @tzawlxih , are you talking about https://github.com/ironPeakServices/hardened-alpine/blob/master/Dockerfile#L93 ? If so, that only removes broken symlinks.
